/*

  This file is a part of EMIPLIB, the EDM Media over IP Library.

  Copyright (C) 2006-2011  Hasselt University - Expertise Centre for
                      Digital Media (EDM) (http://www.edm.uhasselt.be)

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
  USA

*/

/**
 * \file mipsndfileoutput.h
 */

#ifndef MIPOSCOUTPUT_H

#define MIPOSCOUTPUT_H

#include "mipconfig.h"

#ifdef MIPCONFIG_SUPPORT_OSC

#include "mipcomponent.h"
#include "miposcmessage.h"
#include <queue>

/** A OSC output component.
 *  This component stores incoming OSC messages in a queue
 *  No messages are generated by this component.
 */
class EMIPLIB_IMPORTEXPORT MIPOSCOutput : public MIPComponent
{
public:
	MIPOSCOutput();
	~MIPOSCOutput();

	std::queue<MIPOSCMessage *>* messages() { return &m_messages; }

	bool push(const MIPComponentChain &chain, int64_t iteration, MIPMessage *pMsg);
	bool pull(const MIPComponentChain &chain, int64_t iteration, MIPMessage **pMsg);
private:
	std::queue<MIPOSCMessage *> m_messages;
};

#endif // MIPCONFIG_SUPPORT_OSC

#endif // MIPOSCOUTPUT_H

